name = "Dorrel's Adventure Time"
author = "Dorrel Redmond"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "921a724ef91c77b5461342571e3c3a4c4003dfc4bb76d1d18a8ab16f037c62b8"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
